/******************************************************************************
* THIS FILE IS GENERATED ANY CHANGES WILL BE LOST NEXT TIME CODE IS GENERATED *
******************************************************************************/

import {Enum} from './enumify';

class EntityFields extends Enum {}

EntityFields.initEnum([
  ['Number', 'Number', 0],
  ['CustomNumber', 'Custom Number', 1],
  ['Assignee', 'Assignee', 2],
  ['Category', 'Category', 3],
  ['Status', 'Status', 4],
  ['OpenedDate', 'Opened', 5],
  ['RuleGroup', 'Rule Group', 6],
  ['Impact', 'Impact', 7],
  ['ModifiedDate', 'Modified', 8],
  ['ClosedDate', 'Closed', 9],
  ['ServiceContract', 'Service Contract', 10],
  ['Urgency', 'Urgency', 11],
  ['Priority', 'Priority', 12],
  ['CustomChangeType', 'Custom Change Type', 13],
  ['ScheduledImplementationDate', 'Sched. Imp.', 14],
  ['Recipient', 'Recipient', 15],
  ['BillTo', 'Bill to', 16],
  ['RequestedBy', 'Requested by', 17],
  ['CostCenter', 'Cost Center', 18],
  ['JobFunction', 'Job Function', 19],
  ['Customer', 'Customer', 20],
  ['ShortDescription', 'Short Description', 21],
  ['Description', 'Description', 22],
  ['Resolution', 'Resolution', 23],
  ['RootCause', 'Root Cause', 24],
  ['Workaround', 'Workaround', 25],
  ['Reason', 'Reason', 26],
  ['Results', 'Results', 27],
  ['Comments', 'Comments', 28],
  ['Company', 'Company', 29],
  ['RecipientCompany', 'Recipient Company', 30],
  ['BillToCompany', 'Bill to Company', 31],
  ['RequestedByCompany', 'Requested by Company', 32],
  ['Cause', 'Cause', 33],
  ['Steps', 'Steps', 34],
  ['ErrorMessages', 'Error Messages', 35],
  ['URLs', 'URL(s)', 36],
  ['StatusType', 'Status Type', 37],
  ['ChangeType', 'Change Type', 38],
  ['EntityField', 'Entity Field', 39],
  ['GroupLogicOperator', 'Group Logic Operator', 40],
  ['ConditionLogicOperator', 'Condition Logic Operator', 41],
  ['TotalAmount', 'Total Amount', 42],
  ['Likes', 'Likes', 43],
  ['TotalTimeWorked', 'Time Worked', 44],
  ['Name', 'Name', 45],
  ['SerialNumber', 'Serial Number', 46],
  ['TagNumber', 'Tag Number', 47],
  ['Type', 'Type', 48],
  ['Owner', 'Owner', 49],
  ['Vendor', 'Vendor', 50],
  ['Quantity', 'Quantity', 51],
  ['Rate', 'Rate', 52],
  ['Amount', 'Amount', 53],
  ['AssetType', 'Asset Type', 54],
  ['VendorProduct', 'Product', 55],
  ['Question', 'Question', 56],
  ['Answer', 'Answer', 57],
  ['Author', 'Author', 58],
  ['Identifier', 'Identifier', 59],
  ['Duration', 'Duration', 60],
  ['EmailAddress', 'Email Address', 61],
  ['FirstName', 'First Name', 62],
  ['LastName', 'Last Name', 63],
  ['Phone', 'Phone', 64],
  ['Topic', 'Topic', 65],
  ['Message', 'Message', 66],
  ['Details', 'Details', 67],
  ['ExpirationDate', 'Expiration Date', 68],
  ['ChildMessages', 'Child Messages', 69],
  ['FromServiceCatalog', 'From Service Catalog', 70],
  ['Location', 'Location', 71],
  ['CustomerLocation', 'Customer Location', 72],
  ['CustomerDepartment', 'Customer Department', 73],
  ['CustomerGroup', 'Customer Group', 74],
  ['RecipientLocation', 'Recipient Location', 76],
  ['RecipientDepartment', 'Recipient Department', 77],
  ['RecipientGroup', 'Recipient Group', 78],
  ['BillToLocation', 'Bill to Location', 80],
  ['BillToDepartment', 'Bill to Department', 81],
  ['BillToGroup', 'Bill to Group', 82],
  ['RequestedByLocation', 'Requested by Location', 84],
  ['RequestedByDepartment', 'Requested by Department', 85],
  ['RequestedByGroup', 'Requested by Group', 86],
  ['CustomFields', 'Custom Fields', 88],
  ['RepGroup', 'Rep Group', 89],
  ['Rep', 'Rep', 90],
  ['OpportunityStage', 'Stage', 91],
  ['OpportunityType', 'Type', 92],
  ['WallPost', 'Wall Post', 93],
  ['DiscussionFeed', 'Discussion Feed', 94],
  ['ModifiedByCustomer', 'Modified by Customer', 95],
  ['Source', 'Source', 96],
  ['RecipientCustomer', 'Recipient Customer', 97],
  ['BillToCustomer', 'Bill to Customer', 98],
  ['RequestedByCustomer', 'Requested by Customer', 99],
  ['RecipientRep', 'Recipient Rep', 100],
  ['BillToRep', 'Bill to Rep', 101],
  ['RequestedByRep', 'Requested by Rep', 102],
  ['RelatedItems', 'Related Items', 103],
  ['Dislikes', 'Dislikes', 104],
  ['DiscussionPostCreated', 'Created', 105],
  ['DiscussionPostUpdated', 'Updated', 106],
  ['CustomField', 'Custom Field', 107],
]);

export default EntityFields;

/******************************************************************************
* THIS FILE IS GENERATED ANY CHANGES WILL BE LOST NEXT TIME CODE IS GENERATED *
******************************************************************************/
