//@flow
import EntityBase from './entityBase';
import CustomIcon from './CustomIcon';
import SupportRepresentative from './SupportRepresentative';
import Group from './Group';
import IncidentStatus from './IncidentStatus';
import Location from './Location';
import UrgencyImpactMapping from './UrgencyImpactMapping';
import PurchaseStatus from './PurchaseStatus';
import ChangeStatus from './ChangeStatus';
import CustomChangeType from './CustomChangeType';
import SocialClientTheme from './SocialClientTheme';
import IncidentTemplate from './IncidentTemplate';
import SelfHelpGuideItem from './SelfHelpGuideItem';
import FacebookIntegrationInfo from './FacebookIntegrationInfo';
import TwitterIntegrationInfo from './TwitterIntegrationInfo';
import LinkedInIntegrationInfo from './LinkedInIntegrationInfo';
import RepNewsFeedOptions from './RepNewsFeedOptions';
import IncidentLayout from './IncidentLayout';
import ChangeLayout from './ChangeLayout';
import ProblemLayout from './ProblemLayout';
import KnowledgeLayout from './KnowledgeLayout';
import PurchaseLayout from './PurchaseLayout';
import ServiceContractLayout from './ServiceContractLayout';
import QueryChart from './QueryChart';
import CustomerLayout from './CustomerLayout';
import MySupportFeed from './MySupportFeed';
import {IncidentRouteMethod} from './Enums';
import {IncidentPriority} from './Enums';
import {NewHistoryTypes} from './Enums';
import {EntityTypes} from './Enums';
import {SocialClientHomePageMainContentType} from './Enums';
import {SocialClientRightSidePanelType} from './Enums';
import {LayoutPositions} from './Enums';
import {SocialClientMenuTypes} from './Enums';
import {HorizontalAlignment} from './Enums';
import {CompanyEntryOptions} from './Enums';
import {ExternalChatRepNameDisplayTypes} from './Enums';

export class SocialClientOptions extends EntityBase {
  name: string;
  customerDisplayRegistrationLink: string;
  defaultRegisterTitle: string;
  showForgotPasswordLink: string;
  defaultForgotPasswordTitle: string;
  forgotPasswordEmailExpiration: string;
  description: string;
  incidentDisplayWorkHistory: string;
  incidentAllowEmailToAssignee: string;
  changeUpdateEnabled: string;
  useMobileFeedLayout: string;
  incidentSubmitMessage: string;
  incidentSubmitDisplayCustomNumber: string;
  changeSubmitDisplayCustomNumber: string;
  purchaseSubmitDisplayCustomNumber: string;
  incidentLocationOverrideEnabled: string;
  incidentDisplayApprovalHistory: string;
  incidentDisplayApprovalNotification: string;
  problemCreateIncidentEnabled: string;
  changeSubmitMessage: string;
  changeDisplayApprovalHistory: string;
  changeDisplayApprovalAlertBar: string;
  changeDisplayAuditHistory: string;
  changeDisplayCorrespondenceHistory: string;
  changeDisplayCustomerWorkHistory: string;
  changeDisplaySlaHistory: string;
  changeDisplayRuleGroupHistory: string;
  incidentDisplayAuditHistory: string;
  incidentDisplaySlaHistory: string;
  incidentDisplayRuleGroupHistory: string;
  incidentDisplayCorrespondenceHistory: string;
  incidentDisplayCustomerChatHistory: string;
  incidentUpdateAssignee: string;
  incidentUpdateReceiptConfirmation: string;
  changeUpdateReceiptConfirmation: string;
  changeUpdateAssignee: string;
  purchaseDisplayApprovalAlertBar: string;
  purchaseRequestorSubmitterEnabled: string;
  purchaseSubmitMessage: string;
  changeLocationOverrideEnabled: string;
  serviceContractDisplayAuditHistory: string;
  serviceContractDisplayCorrespondenceHistory: string;
  serviceContractUseWithIncident: string;
  serviceContractUseWithChange: string;
  serviceContractNoContractMessage: string;
  serviceContractCourtesyTicketsEnabled: string;
  incidentDisplayGenericCustomerAuditHistory: string;
  changeDisplayGenericCustomerAuditHistory: string;
  bomgarIncidentDisplayNewSessionLink: string;
  bomgarIncidentCreateIncidentOnNewSessionStart: string;
  bomgarLoginRequiredForNewSession: string;
  bomgarDisplayAvailableReps: string;
  bomgarChatFlyoutEnabled: string;
  bomgarChatFlyoutTitle: string;
  bomgarChatFlyoutIcon: string;
  bomgarChatFlyoutContent: string;
  bomgarChatFlyoutDelay: string;
  bomgarMaxActiveEventsCount: string;
  homePageDisplayWelcomeMessage: string;
  homePageWelcomeMessage: string;
  homePageDisplayAssistBar: string;
  homePageRightSidePanel1Parameter: string;
  homePageRightSidePanel2Parameter: string;
  knowledgeEntryPageDisplayCategoryTree: string;
  knowledgeEntryPageDisplayCategoryTiles: string;
  knowledgeEntryPageWidget1Parameter: string;
  knowledgeEntryPageWidget2Parameter: string;
  incidentSelectCategoryText: string;
  changeSelectCategoryText: string;
  knowledgeSelectCategoryText: string;
  smsNotificationsEnabled: string;
  problemDisplayAuditHistory: string;
  problemDisplayCorrespondenceHistory: string;
  problemDisplayRuleGroupHistory: string;
  knowledgeEntryShowFollowLink: string;
  knowledgeEntryShowFollowButton: string;
  knowledgeEntryShowLikeButton: string;
  chatEnabled: string;
  chatAllowUnauthenticated: string;
  chatShowLinkOnIncident: string;
  chatRequestTimeoutLength: string;
  chatTimeoutMessage: string;
  chatTimeoutCreateIncidentButtonIncluded: string;
  chatShowGroupSelection: string;
  chatFlyoutEnabled: string;
  chatFlyoutTitle: string;
  chatFlyoutIcon: string;
  chatFlyoutContent: string;
  chatFlyoutDelay: string;
  newUsersRequireReview: string;
  newUsersRequireReviewMessage: string;
  loginBackgroundImage: string;
  loginBackgroundImageRepeat: string;
  knowledgeEntryShowHistoryContents: string;
  goToAssistShowLinkOnIncident: string;
  goToAssistClientUrl: string;
  goToAssistFlyoutEnabled: string;
  goToAssistFlyoutTitle: string;
  goToAssistFlyoutIcon: string;
  goToAssistFlyoutContent: string;
  goToAssistFlyoutDelay: string;
  incidentDisplayCategory: string;
  changeDisplayCategory: string;
  problemDisplayCategory: string;
  knowledgeEntryDisplayCategory: string;
  incidentEditCategory: string;
  changeEditCategory: string;
  incidentDisplayTabOrder: string;
  changeDisplayTabOrder: string;
  problemDisplayTabOrder: string;
  purchaseDisplayTabOrder: string;
  knowledgeEntryDisplayTabOrder: string;
  serviceContractDisplayTabOrder: string;
  incidentDisplayFieldOrder: string;
  changeDisplayFieldOrder: string;
  problemDisplayFieldOrder: string;
  purchaseDisplayFieldOrder: string;
  knowledgeEntryDisplayFieldOrder: string;
  serviceContractDisplayFieldOrder: string;
  incidentEditTabOrder: string;
  changeEditTabOrder: string;
  purchaseEditTabOrder: string;
  incidentEditFieldOrder: string;
  changeEditFieldOrder: string;
  purchaseEditFieldOrder: string;
  showCompanyOnRegistration: string;
  showPhoneOnRegistration: string;
  showCompanyOnIncidentSubmit: string;
  requireCompanyOnIncidentSubmit: string;
  showLocationOnIncidentSubmit: string;
  requireLocationOnIncidentSubmit: string;
  showPhoneOnIncidentSubmit: string;
  requirePhoneOnIncidentSubmit: string;
  showCompanyOnChangeSubmit: string;
  requireCompanyOnChangeSubmit: string;
  showLocationOnChangeSubmit: string;
  requireLocationOnChangeSubmit: string;
  showPhoneOnChangeSubmit: string;
  requirePhoneOnChangeSubmit: string;
  shippingCreateWorkItemIcon: string;
  shippingDisplaySelfHelpGuideIcon: string;
  shippingCreateDiscussionPostIcon: string;
  headerGaugeText: string;
  tiledNavigatorMaxColumns: string;
  assistBarTextOverride: string;
  customersCanAddDashboards: string;
  customerShowTimeZonePrompt: string;
  availableWidgets: string;
  pinNavigatorByDefault: string;
  sanitizeHtml: string;
  chatRepOtherDisplayName: string;
  incidentRouteMethod: IncidentRouteMethod;
  incidentDefaultPriority: IncidentPriority;
  purchaseHistoryTypesToDisplay: NewHistoryTypes;
  changeRouteMethod: IncidentRouteMethod;
  assistBarSearchEntityTypes: EntityTypes;
  homePageMainContentType: SocialClientHomePageMainContentType;
  homePageRightSidePanel1Type: SocialClientRightSidePanelType;
  homePageRightSidePanel2Type: SocialClientRightSidePanelType;
  knowledgeEntryPageWidget1Type: SocialClientRightSidePanelType;
  knowledgeEntryPageWidget2Type: SocialClientRightSidePanelType;
  globalAssistBarCreateEntityTypes: EntityTypes;
  chatButtomPosition: LayoutPositions;
  menuType: SocialClientMenuTypes;
  tiledNavigatorAlignment: HorizontalAlignment;
  incidentSubmitCompanyEntryType: CompanyEntryOptions;
  changeSubmitCompanyEntryType: CompanyEntryOptions;
  chatRepNameDisplayType: ExternalChatRepNameDisplayTypes;
  createWorkItemIcon: CustomIcon;
  displaySelfHelpGuideIcon: CustomIcon;
  createDiscussionPostIcon: CustomIcon;
  incidentDefaultOwner: SupportRepresentative;
  incidentDefaultOwnerGroup: Group;
  incidentDefaultStatus: IncidentStatus;
  incidentLoadBalancedRouteGroup: Group;
  incidentLoadBalancedRouteLocation: Location;
  incidentDefaultUrgencyImpactMapping: UrgencyImpactMapping;
  purchaseDefaultStatus: PurchaseStatus;
  changeDefaultOwner: SupportRepresentative;
  changeDefaultOwnerGroup: Group;
  changeDefaultStatus: ChangeStatus;
  changeLoadBalancedRouteGroup: Group;
  changeLoadBalancedRouteLocation: Location;
  changeDefaultUrgencyImpactMapping: UrgencyImpactMapping;
  changeDefaultCustomChangeType: CustomChangeType;
  theme: SocialClientTheme;
  bomgarIncidentTemplactForNewSessions: IncidentTemplate;
  globalAssistBarSelfHelpGuide: SelfHelpGuideItem;
  facebookIntegrationInfo: FacebookIntegrationInfo;
  twitterIntegrationInfo: TwitterIntegrationInfo;
  linkedInIntegrationInfo: LinkedInIntegrationInfo;
  forgotLoginTemplate: IncidentTemplate;
  knowledgeDiscussionNewsFeed: RepNewsFeedOptions;
  incidentTemplaceForCustomerRequiresReview: IncidentTemplate;
  viewIncidentLayout: IncidentLayout;
  submitIncidentLayout: IncidentLayout;
  viewChangeLayout: ChangeLayout;
  submitChangeLayout: ChangeLayout;
  viewProblemLayout: ProblemLayout;
  viewKnowledgeLayout: KnowledgeLayout;
  viewPurchaseLayout: PurchaseLayout;
  submitPurchaseLayout: PurchaseLayout;
  viewServiceContractLayout: ServiceContractLayout;
  headerGauge: QueryChart;
  customerProfileLayout: CustomerLayout;
  incidentFeed: MySupportFeed;
  changeFeed: MySupportFeed;
  problemFeed: MySupportFeed;
  purchaseFeed: MySupportFeed;
  knowledgeEntryFeed: MySupportFeed;
  serviceContractFeed: MySupportFeed;
  headlineFeed: MySupportFeed;

  static fromApiEntity(apiSocialClientOptions:SocialClientOptionsType): SocialClientOptions {
    let socialClientOptions = new SocialClientOptions();
    socialClientOptions.id = apiSocialClientOptions.id;
    socialClientOptions.name = apiSocialClientOptions.name;
    socialClientOptions.customerDisplayRegistrationLink = apiSocialClientOptions.customerDisplayRegistrationLink;
    socialClientOptions.defaultRegisterTitle = apiSocialClientOptions.defaultRegisterTitle;
    socialClientOptions.showForgotPasswordLink = apiSocialClientOptions.showForgotPasswordLink;
    socialClientOptions.defaultForgotPasswordTitle = apiSocialClientOptions.defaultForgotPasswordTitle;
    socialClientOptions.forgotPasswordEmailExpiration = apiSocialClientOptions.forgotPasswordEmailExpiration;
    socialClientOptions.description = apiSocialClientOptions.description;
    socialClientOptions.incidentDisplayWorkHistory = apiSocialClientOptions.incidentDisplayWorkHistory;
    socialClientOptions.incidentAllowEmailToAssignee = apiSocialClientOptions.incidentAllowEmailToAssignee;
    socialClientOptions.changeUpdateEnabled = apiSocialClientOptions.changeUpdateEnabled;
    socialClientOptions.useMobileFeedLayout = apiSocialClientOptions.useMobileFeedLayout;
    socialClientOptions.incidentSubmitMessage = apiSocialClientOptions.incidentSubmitMessage;
    socialClientOptions.incidentSubmitDisplayCustomNumber = apiSocialClientOptions.incidentSubmitDisplayCustomNumber;
    socialClientOptions.changeSubmitDisplayCustomNumber = apiSocialClientOptions.changeSubmitDisplayCustomNumber;
    socialClientOptions.purchaseSubmitDisplayCustomNumber = apiSocialClientOptions.purchaseSubmitDisplayCustomNumber;
    socialClientOptions.incidentLocationOverrideEnabled = apiSocialClientOptions.incidentLocationOverrideEnabled;
    socialClientOptions.incidentDisplayApprovalHistory = apiSocialClientOptions.incidentDisplayApprovalHistory;
    socialClientOptions.incidentDisplayApprovalNotification = apiSocialClientOptions.incidentDisplayApprovalNotification;
    socialClientOptions.problemCreateIncidentEnabled = apiSocialClientOptions.problemCreateIncidentEnabled;
    socialClientOptions.changeSubmitMessage = apiSocialClientOptions.changeSubmitMessage;
    socialClientOptions.changeDisplayApprovalHistory = apiSocialClientOptions.changeDisplayApprovalHistory;
    socialClientOptions.changeDisplayApprovalAlertBar = apiSocialClientOptions.changeDisplayApprovalAlertBar;
    socialClientOptions.changeDisplayAuditHistory = apiSocialClientOptions.changeDisplayAuditHistory;
    socialClientOptions.changeDisplayCorrespondenceHistory = apiSocialClientOptions.changeDisplayCorrespondenceHistory;
    socialClientOptions.changeDisplayCustomerWorkHistory = apiSocialClientOptions.changeDisplayCustomerWorkHistory;
    socialClientOptions.changeDisplaySlaHistory = apiSocialClientOptions.changeDisplaySlaHistory;
    socialClientOptions.changeDisplayRuleGroupHistory = apiSocialClientOptions.changeDisplayRuleGroupHistory;
    socialClientOptions.incidentDisplayAuditHistory = apiSocialClientOptions.incidentDisplayAuditHistory;
    socialClientOptions.incidentDisplaySlaHistory = apiSocialClientOptions.incidentDisplaySlaHistory;
    socialClientOptions.incidentDisplayRuleGroupHistory = apiSocialClientOptions.incidentDisplayRuleGroupHistory;
    socialClientOptions.incidentDisplayCorrespondenceHistory = apiSocialClientOptions.incidentDisplayCorrespondenceHistory;
    socialClientOptions.incidentDisplayCustomerChatHistory = apiSocialClientOptions.incidentDisplayCustomerChatHistory;
    socialClientOptions.incidentUpdateAssignee = apiSocialClientOptions.incidentUpdateAssignee;
    socialClientOptions.incidentUpdateReceiptConfirmation = apiSocialClientOptions.incidentUpdateReceiptConfirmation;
    socialClientOptions.changeUpdateReceiptConfirmation = apiSocialClientOptions.changeUpdateReceiptConfirmation;
    socialClientOptions.changeUpdateAssignee = apiSocialClientOptions.changeUpdateAssignee;
    socialClientOptions.purchaseDisplayApprovalAlertBar = apiSocialClientOptions.purchaseDisplayApprovalAlertBar;
    socialClientOptions.purchaseRequestorSubmitterEnabled = apiSocialClientOptions.purchaseRequestorSubmitterEnabled;
    socialClientOptions.purchaseSubmitMessage = apiSocialClientOptions.purchaseSubmitMessage;
    socialClientOptions.changeLocationOverrideEnabled = apiSocialClientOptions.changeLocationOverrideEnabled;
    socialClientOptions.serviceContractDisplayAuditHistory = apiSocialClientOptions.serviceContractDisplayAuditHistory;
    socialClientOptions.serviceContractDisplayCorrespondenceHistory = apiSocialClientOptions.serviceContractDisplayCorrespondenceHistory;
    socialClientOptions.serviceContractUseWithIncident = apiSocialClientOptions.serviceContractUseWithIncident;
    socialClientOptions.serviceContractUseWithChange = apiSocialClientOptions.serviceContractUseWithChange;
    socialClientOptions.serviceContractNoContractMessage = apiSocialClientOptions.serviceContractNoContractMessage;
    socialClientOptions.serviceContractCourtesyTicketsEnabled = apiSocialClientOptions.serviceContractCourtesyTicketsEnabled;
    socialClientOptions.incidentDisplayGenericCustomerAuditHistory = apiSocialClientOptions.incidentDisplayGenericCustomerAuditHistory;
    socialClientOptions.changeDisplayGenericCustomerAuditHistory = apiSocialClientOptions.changeDisplayGenericCustomerAuditHistory;
    socialClientOptions.bomgarIncidentDisplayNewSessionLink = apiSocialClientOptions.bomgarIncidentDisplayNewSessionLink;
    socialClientOptions.bomgarIncidentCreateIncidentOnNewSessionStart = apiSocialClientOptions.bomgarIncidentCreateIncidentOnNewSessionStart;
    socialClientOptions.bomgarLoginRequiredForNewSession = apiSocialClientOptions.bomgarLoginRequiredForNewSession;
    socialClientOptions.bomgarDisplayAvailableReps = apiSocialClientOptions.bomgarDisplayAvailableReps;
    socialClientOptions.bomgarChatFlyoutEnabled = apiSocialClientOptions.bomgarChatFlyoutEnabled;
    socialClientOptions.bomgarChatFlyoutTitle = apiSocialClientOptions.bomgarChatFlyoutTitle;
    socialClientOptions.bomgarChatFlyoutIcon = apiSocialClientOptions.bomgarChatFlyoutIcon;
    socialClientOptions.bomgarChatFlyoutContent = apiSocialClientOptions.bomgarChatFlyoutContent;
    socialClientOptions.bomgarChatFlyoutDelay = apiSocialClientOptions.bomgarChatFlyoutDelay;
    socialClientOptions.bomgarMaxActiveEventsCount = apiSocialClientOptions.bomgarMaxActiveEventsCount;
    socialClientOptions.homePageDisplayWelcomeMessage = apiSocialClientOptions.homePageDisplayWelcomeMessage;
    socialClientOptions.homePageWelcomeMessage = apiSocialClientOptions.homePageWelcomeMessage;
    socialClientOptions.homePageDisplayAssistBar = apiSocialClientOptions.homePageDisplayAssistBar;
    socialClientOptions.homePageRightSidePanel1Parameter = apiSocialClientOptions.homePageRightSidePanel1Parameter;
    socialClientOptions.homePageRightSidePanel2Parameter = apiSocialClientOptions.homePageRightSidePanel2Parameter;
    socialClientOptions.knowledgeEntryPageDisplayCategoryTree = apiSocialClientOptions.knowledgeEntryPageDisplayCategoryTree;
    socialClientOptions.knowledgeEntryPageDisplayCategoryTiles = apiSocialClientOptions.knowledgeEntryPageDisplayCategoryTiles;
    socialClientOptions.knowledgeEntryPageWidget1Parameter = apiSocialClientOptions.knowledgeEntryPageWidget1Parameter;
    socialClientOptions.knowledgeEntryPageWidget2Parameter = apiSocialClientOptions.knowledgeEntryPageWidget2Parameter;
    socialClientOptions.incidentSelectCategoryText = apiSocialClientOptions.incidentSelectCategoryText;
    socialClientOptions.changeSelectCategoryText = apiSocialClientOptions.changeSelectCategoryText;
    socialClientOptions.knowledgeSelectCategoryText = apiSocialClientOptions.knowledgeSelectCategoryText;
    socialClientOptions.smsNotificationsEnabled = apiSocialClientOptions.smsNotificationsEnabled;
    socialClientOptions.problemDisplayAuditHistory = apiSocialClientOptions.problemDisplayAuditHistory;
    socialClientOptions.problemDisplayCorrespondenceHistory = apiSocialClientOptions.problemDisplayCorrespondenceHistory;
    socialClientOptions.problemDisplayRuleGroupHistory = apiSocialClientOptions.problemDisplayRuleGroupHistory;
    socialClientOptions.knowledgeEntryShowFollowLink = apiSocialClientOptions.knowledgeEntryShowFollowLink;
    socialClientOptions.knowledgeEntryShowFollowButton = apiSocialClientOptions.knowledgeEntryShowFollowButton;
    socialClientOptions.knowledgeEntryShowLikeButton = apiSocialClientOptions.knowledgeEntryShowLikeButton;
    socialClientOptions.chatEnabled = apiSocialClientOptions.chatEnabled;
    socialClientOptions.chatAllowUnauthenticated = apiSocialClientOptions.chatAllowUnauthenticated;
    socialClientOptions.chatShowLinkOnIncident = apiSocialClientOptions.chatShowLinkOnIncident;
    socialClientOptions.chatRequestTimeoutLength = apiSocialClientOptions.chatRequestTimeoutLength;
    socialClientOptions.chatTimeoutMessage = apiSocialClientOptions.chatTimeoutMessage;
    socialClientOptions.chatTimeoutCreateIncidentButtonIncluded = apiSocialClientOptions.chatTimeoutCreateIncidentButtonIncluded;
    socialClientOptions.chatShowGroupSelection = apiSocialClientOptions.chatShowGroupSelection;
    socialClientOptions.chatFlyoutEnabled = apiSocialClientOptions.chatFlyoutEnabled;
    socialClientOptions.chatFlyoutTitle = apiSocialClientOptions.chatFlyoutTitle;
    socialClientOptions.chatFlyoutIcon = apiSocialClientOptions.chatFlyoutIcon;
    socialClientOptions.chatFlyoutContent = apiSocialClientOptions.chatFlyoutContent;
    socialClientOptions.chatFlyoutDelay = apiSocialClientOptions.chatFlyoutDelay;
    socialClientOptions.newUsersRequireReview = apiSocialClientOptions.newUsersRequireReview;
    socialClientOptions.newUsersRequireReviewMessage = apiSocialClientOptions.newUsersRequireReviewMessage;
    socialClientOptions.loginBackgroundImage = apiSocialClientOptions.loginBackgroundImage;
    socialClientOptions.loginBackgroundImageRepeat = apiSocialClientOptions.loginBackgroundImageRepeat;
    socialClientOptions.knowledgeEntryShowHistoryContents = apiSocialClientOptions.knowledgeEntryShowHistoryContents;
    socialClientOptions.goToAssistShowLinkOnIncident = apiSocialClientOptions.goToAssistShowLinkOnIncident;
    socialClientOptions.goToAssistClientUrl = apiSocialClientOptions.goToAssistClientUrl;
    socialClientOptions.goToAssistFlyoutEnabled = apiSocialClientOptions.goToAssistFlyoutEnabled;
    socialClientOptions.goToAssistFlyoutTitle = apiSocialClientOptions.goToAssistFlyoutTitle;
    socialClientOptions.goToAssistFlyoutIcon = apiSocialClientOptions.goToAssistFlyoutIcon;
    socialClientOptions.goToAssistFlyoutContent = apiSocialClientOptions.goToAssistFlyoutContent;
    socialClientOptions.goToAssistFlyoutDelay = apiSocialClientOptions.goToAssistFlyoutDelay;
    socialClientOptions.incidentDisplayCategory = apiSocialClientOptions.incidentDisplayCategory;
    socialClientOptions.changeDisplayCategory = apiSocialClientOptions.changeDisplayCategory;
    socialClientOptions.problemDisplayCategory = apiSocialClientOptions.problemDisplayCategory;
    socialClientOptions.knowledgeEntryDisplayCategory = apiSocialClientOptions.knowledgeEntryDisplayCategory;
    socialClientOptions.incidentEditCategory = apiSocialClientOptions.incidentEditCategory;
    socialClientOptions.changeEditCategory = apiSocialClientOptions.changeEditCategory;
    socialClientOptions.incidentDisplayTabOrder = apiSocialClientOptions.incidentDisplayTabOrder;
    socialClientOptions.changeDisplayTabOrder = apiSocialClientOptions.changeDisplayTabOrder;
    socialClientOptions.problemDisplayTabOrder = apiSocialClientOptions.problemDisplayTabOrder;
    socialClientOptions.purchaseDisplayTabOrder = apiSocialClientOptions.purchaseDisplayTabOrder;
    socialClientOptions.knowledgeEntryDisplayTabOrder = apiSocialClientOptions.knowledgeEntryDisplayTabOrder;
    socialClientOptions.serviceContractDisplayTabOrder = apiSocialClientOptions.serviceContractDisplayTabOrder;
    socialClientOptions.incidentDisplayFieldOrder = apiSocialClientOptions.incidentDisplayFieldOrder;
    socialClientOptions.changeDisplayFieldOrder = apiSocialClientOptions.changeDisplayFieldOrder;
    socialClientOptions.problemDisplayFieldOrder = apiSocialClientOptions.problemDisplayFieldOrder;
    socialClientOptions.purchaseDisplayFieldOrder = apiSocialClientOptions.purchaseDisplayFieldOrder;
    socialClientOptions.knowledgeEntryDisplayFieldOrder = apiSocialClientOptions.knowledgeEntryDisplayFieldOrder;
    socialClientOptions.serviceContractDisplayFieldOrder = apiSocialClientOptions.serviceContractDisplayFieldOrder;
    socialClientOptions.incidentEditTabOrder = apiSocialClientOptions.incidentEditTabOrder;
    socialClientOptions.changeEditTabOrder = apiSocialClientOptions.changeEditTabOrder;
    socialClientOptions.purchaseEditTabOrder = apiSocialClientOptions.purchaseEditTabOrder;
    socialClientOptions.incidentEditFieldOrder = apiSocialClientOptions.incidentEditFieldOrder;
    socialClientOptions.changeEditFieldOrder = apiSocialClientOptions.changeEditFieldOrder;
    socialClientOptions.purchaseEditFieldOrder = apiSocialClientOptions.purchaseEditFieldOrder;
    socialClientOptions.showCompanyOnRegistration = apiSocialClientOptions.showCompanyOnRegistration;
    socialClientOptions.showPhoneOnRegistration = apiSocialClientOptions.showPhoneOnRegistration;
    socialClientOptions.showCompanyOnIncidentSubmit = apiSocialClientOptions.showCompanyOnIncidentSubmit;
    socialClientOptions.requireCompanyOnIncidentSubmit = apiSocialClientOptions.requireCompanyOnIncidentSubmit;
    socialClientOptions.showLocationOnIncidentSubmit = apiSocialClientOptions.showLocationOnIncidentSubmit;
    socialClientOptions.requireLocationOnIncidentSubmit = apiSocialClientOptions.requireLocationOnIncidentSubmit;
    socialClientOptions.showPhoneOnIncidentSubmit = apiSocialClientOptions.showPhoneOnIncidentSubmit;
    socialClientOptions.requirePhoneOnIncidentSubmit = apiSocialClientOptions.requirePhoneOnIncidentSubmit;
    socialClientOptions.showCompanyOnChangeSubmit = apiSocialClientOptions.showCompanyOnChangeSubmit;
    socialClientOptions.requireCompanyOnChangeSubmit = apiSocialClientOptions.requireCompanyOnChangeSubmit;
    socialClientOptions.showLocationOnChangeSubmit = apiSocialClientOptions.showLocationOnChangeSubmit;
    socialClientOptions.requireLocationOnChangeSubmit = apiSocialClientOptions.requireLocationOnChangeSubmit;
    socialClientOptions.showPhoneOnChangeSubmit = apiSocialClientOptions.showPhoneOnChangeSubmit;
    socialClientOptions.requirePhoneOnChangeSubmit = apiSocialClientOptions.requirePhoneOnChangeSubmit;
    socialClientOptions.shippingCreateWorkItemIcon = apiSocialClientOptions.shippingCreateWorkItemIcon;
    socialClientOptions.shippingDisplaySelfHelpGuideIcon = apiSocialClientOptions.shippingDisplaySelfHelpGuideIcon;
    socialClientOptions.shippingCreateDiscussionPostIcon = apiSocialClientOptions.shippingCreateDiscussionPostIcon;
    socialClientOptions.headerGaugeText = apiSocialClientOptions.headerGaugeText;
    socialClientOptions.tiledNavigatorMaxColumns = apiSocialClientOptions.tiledNavigatorMaxColumns;
    socialClientOptions.assistBarTextOverride = apiSocialClientOptions.assistBarTextOverride;
    socialClientOptions.customersCanAddDashboards = apiSocialClientOptions.customersCanAddDashboards;
    socialClientOptions.customerShowTimeZonePrompt = apiSocialClientOptions.customerShowTimeZonePrompt;
    socialClientOptions.availableWidgets = apiSocialClientOptions.availableWidgets;
    socialClientOptions.pinNavigatorByDefault = apiSocialClientOptions.pinNavigatorByDefault;
    socialClientOptions.sanitizeHtml = apiSocialClientOptions.sanitizeHtml;
    socialClientOptions.chatRepOtherDisplayName = apiSocialClientOptions.chatRepOtherDisplayName;
    socialClientOptions.incidentRouteMethod = IncidentRouteMethod.enumOrdinalOf(parseInt(apiSocialClientOptions.incidentRouteMethod, 10));
    socialClientOptions.incidentDefaultPriority = IncidentPriority.enumOrdinalOf(parseInt(apiSocialClientOptions.incidentDefaultPriority, 10));
    socialClientOptions.purchaseHistoryTypesToDisplay = NewHistoryTypes.enumOrdinalOf(parseInt(apiSocialClientOptions.purchaseHistoryTypesToDisplay, 10));
    socialClientOptions.changeRouteMethod = IncidentRouteMethod.enumOrdinalOf(parseInt(apiSocialClientOptions.changeRouteMethod, 10));
    socialClientOptions.assistBarSearchEntityTypes = EntityTypes.enumOrdinalOf(parseInt(apiSocialClientOptions.assistBarSearchEntityTypes, 10));
    socialClientOptions.homePageMainContentType = SocialClientHomePageMainContentType.enumOrdinalOf(parseInt(apiSocialClientOptions.homePageMainContentType, 10));
    socialClientOptions.homePageRightSidePanel1Type = SocialClientRightSidePanelType.enumOrdinalOf(parseInt(apiSocialClientOptions.homePageRightSidePanel1Type, 10));
    socialClientOptions.homePageRightSidePanel2Type = SocialClientRightSidePanelType.enumOrdinalOf(parseInt(apiSocialClientOptions.homePageRightSidePanel2Type, 10));
    socialClientOptions.knowledgeEntryPageWidget1Type = SocialClientRightSidePanelType.enumOrdinalOf(parseInt(apiSocialClientOptions.knowledgeEntryPageWidget1Type, 10));
    socialClientOptions.knowledgeEntryPageWidget2Type = SocialClientRightSidePanelType.enumOrdinalOf(parseInt(apiSocialClientOptions.knowledgeEntryPageWidget2Type, 10));
    socialClientOptions.globalAssistBarCreateEntityTypes = EntityTypes.enumOrdinalOf(parseInt(apiSocialClientOptions.globalAssistBarCreateEntityTypes, 10));
    socialClientOptions.chatButtomPosition = LayoutPositions.enumOrdinalOf(parseInt(apiSocialClientOptions.chatButtomPosition, 10));
    socialClientOptions.menuType = SocialClientMenuTypes.enumOrdinalOf(parseInt(apiSocialClientOptions.menuType, 10));
    socialClientOptions.tiledNavigatorAlignment = HorizontalAlignment.enumOrdinalOf(parseInt(apiSocialClientOptions.tiledNavigatorAlignment, 10));
    socialClientOptions.incidentSubmitCompanyEntryType = CompanyEntryOptions.enumOrdinalOf(parseInt(apiSocialClientOptions.incidentSubmitCompanyEntryType, 10));
    socialClientOptions.changeSubmitCompanyEntryType = CompanyEntryOptions.enumOrdinalOf(parseInt(apiSocialClientOptions.changeSubmitCompanyEntryType, 10));
    socialClientOptions.chatRepNameDisplayType = ExternalChatRepNameDisplayTypes.enumOrdinalOf(parseInt(apiSocialClientOptions.chatRepNameDisplayType, 10));
    if (apiSocialClientOptions.createWorkItemIcon) socialClientOptions.createWorkItemIcon = CustomIcon.fromApiEntity(apiSocialClientOptions.createWorkItemIcon);
    if (apiSocialClientOptions.displaySelfHelpGuideIcon) socialClientOptions.displaySelfHelpGuideIcon = CustomIcon.fromApiEntity(apiSocialClientOptions.displaySelfHelpGuideIcon);
    if (apiSocialClientOptions.createDiscussionPostIcon) socialClientOptions.createDiscussionPostIcon = CustomIcon.fromApiEntity(apiSocialClientOptions.createDiscussionPostIcon);
    if (apiSocialClientOptions.incidentDefaultOwner) socialClientOptions.incidentDefaultOwner = SupportRepresentative.fromApiEntity(apiSocialClientOptions.incidentDefaultOwner);
    if (apiSocialClientOptions.incidentDefaultOwnerGroup) socialClientOptions.incidentDefaultOwnerGroup = Group.fromApiEntity(apiSocialClientOptions.incidentDefaultOwnerGroup);
    if (apiSocialClientOptions.incidentDefaultStatus) socialClientOptions.incidentDefaultStatus = IncidentStatus.fromApiEntity(apiSocialClientOptions.incidentDefaultStatus);
    if (apiSocialClientOptions.incidentLoadBalancedRouteGroup) socialClientOptions.incidentLoadBalancedRouteGroup = Group.fromApiEntity(apiSocialClientOptions.incidentLoadBalancedRouteGroup);
    if (apiSocialClientOptions.incidentLoadBalancedRouteLocation) socialClientOptions.incidentLoadBalancedRouteLocation = Location.fromApiEntity(apiSocialClientOptions.incidentLoadBalancedRouteLocation);
    if (apiSocialClientOptions.incidentDefaultUrgencyImpactMapping) socialClientOptions.incidentDefaultUrgencyImpactMapping = UrgencyImpactMapping.fromApiEntity(apiSocialClientOptions.incidentDefaultUrgencyImpactMapping);
    if (apiSocialClientOptions.purchaseDefaultStatus) socialClientOptions.purchaseDefaultStatus = PurchaseStatus.fromApiEntity(apiSocialClientOptions.purchaseDefaultStatus);
    if (apiSocialClientOptions.changeDefaultOwner) socialClientOptions.changeDefaultOwner = SupportRepresentative.fromApiEntity(apiSocialClientOptions.changeDefaultOwner);
    if (apiSocialClientOptions.changeDefaultOwnerGroup) socialClientOptions.changeDefaultOwnerGroup = Group.fromApiEntity(apiSocialClientOptions.changeDefaultOwnerGroup);
    if (apiSocialClientOptions.changeDefaultStatus) socialClientOptions.changeDefaultStatus = ChangeStatus.fromApiEntity(apiSocialClientOptions.changeDefaultStatus);
    if (apiSocialClientOptions.changeLoadBalancedRouteGroup) socialClientOptions.changeLoadBalancedRouteGroup = Group.fromApiEntity(apiSocialClientOptions.changeLoadBalancedRouteGroup);
    if (apiSocialClientOptions.changeLoadBalancedRouteLocation) socialClientOptions.changeLoadBalancedRouteLocation = Location.fromApiEntity(apiSocialClientOptions.changeLoadBalancedRouteLocation);
    if (apiSocialClientOptions.changeDefaultUrgencyImpactMapping) socialClientOptions.changeDefaultUrgencyImpactMapping = UrgencyImpactMapping.fromApiEntity(apiSocialClientOptions.changeDefaultUrgencyImpactMapping);
    if (apiSocialClientOptions.changeDefaultCustomChangeType) socialClientOptions.changeDefaultCustomChangeType = CustomChangeType.fromApiEntity(apiSocialClientOptions.changeDefaultCustomChangeType);
    if (apiSocialClientOptions.theme) socialClientOptions.theme = SocialClientTheme.fromApiEntity(apiSocialClientOptions.theme);
    if (apiSocialClientOptions.bomgarIncidentTemplactForNewSessions) socialClientOptions.bomgarIncidentTemplactForNewSessions = IncidentTemplate.fromApiEntity(apiSocialClientOptions.bomgarIncidentTemplactForNewSessions);
    if (apiSocialClientOptions.globalAssistBarSelfHelpGuide) socialClientOptions.globalAssistBarSelfHelpGuide = SelfHelpGuideItem.fromApiEntity(apiSocialClientOptions.globalAssistBarSelfHelpGuide);
    if (apiSocialClientOptions.facebookIntegrationInfo) socialClientOptions.facebookIntegrationInfo = FacebookIntegrationInfo.fromApiEntity(apiSocialClientOptions.facebookIntegrationInfo);
    if (apiSocialClientOptions.twitterIntegrationInfo) socialClientOptions.twitterIntegrationInfo = TwitterIntegrationInfo.fromApiEntity(apiSocialClientOptions.twitterIntegrationInfo);
    if (apiSocialClientOptions.linkedInIntegrationInfo) socialClientOptions.linkedInIntegrationInfo = LinkedInIntegrationInfo.fromApiEntity(apiSocialClientOptions.linkedInIntegrationInfo);
    if (apiSocialClientOptions.forgotLoginTemplate) socialClientOptions.forgotLoginTemplate = IncidentTemplate.fromApiEntity(apiSocialClientOptions.forgotLoginTemplate);
    if (apiSocialClientOptions.knowledgeDiscussionNewsFeed) socialClientOptions.knowledgeDiscussionNewsFeed = RepNewsFeedOptions.fromApiEntity(apiSocialClientOptions.knowledgeDiscussionNewsFeed);
    if (apiSocialClientOptions.incidentTemplaceForCustomerRequiresReview) socialClientOptions.incidentTemplaceForCustomerRequiresReview = IncidentTemplate.fromApiEntity(apiSocialClientOptions.incidentTemplaceForCustomerRequiresReview);
    if (apiSocialClientOptions.viewIncidentLayout) socialClientOptions.viewIncidentLayout = IncidentLayout.fromApiEntity(apiSocialClientOptions.viewIncidentLayout);
    if (apiSocialClientOptions.submitIncidentLayout) socialClientOptions.submitIncidentLayout = IncidentLayout.fromApiEntity(apiSocialClientOptions.submitIncidentLayout);
    if (apiSocialClientOptions.viewChangeLayout) socialClientOptions.viewChangeLayout = ChangeLayout.fromApiEntity(apiSocialClientOptions.viewChangeLayout);
    if (apiSocialClientOptions.submitChangeLayout) socialClientOptions.submitChangeLayout = ChangeLayout.fromApiEntity(apiSocialClientOptions.submitChangeLayout);
    if (apiSocialClientOptions.viewProblemLayout) socialClientOptions.viewProblemLayout = ProblemLayout.fromApiEntity(apiSocialClientOptions.viewProblemLayout);
    if (apiSocialClientOptions.viewKnowledgeLayout) socialClientOptions.viewKnowledgeLayout = KnowledgeLayout.fromApiEntity(apiSocialClientOptions.viewKnowledgeLayout);
    if (apiSocialClientOptions.viewPurchaseLayout) socialClientOptions.viewPurchaseLayout = PurchaseLayout.fromApiEntity(apiSocialClientOptions.viewPurchaseLayout);
    if (apiSocialClientOptions.submitPurchaseLayout) socialClientOptions.submitPurchaseLayout = PurchaseLayout.fromApiEntity(apiSocialClientOptions.submitPurchaseLayout);
    if (apiSocialClientOptions.viewServiceContractLayout) socialClientOptions.viewServiceContractLayout = ServiceContractLayout.fromApiEntity(apiSocialClientOptions.viewServiceContractLayout);
    if (apiSocialClientOptions.headerGauge) socialClientOptions.headerGauge = QueryChart.fromApiEntity(apiSocialClientOptions.headerGauge);
    if (apiSocialClientOptions.customerProfileLayout) socialClientOptions.customerProfileLayout = CustomerLayout.fromApiEntity(apiSocialClientOptions.customerProfileLayout);
    if (apiSocialClientOptions.incidentFeed) socialClientOptions.incidentFeed = MySupportFeed.fromApiEntity(apiSocialClientOptions.incidentFeed);
    if (apiSocialClientOptions.changeFeed) socialClientOptions.changeFeed = MySupportFeed.fromApiEntity(apiSocialClientOptions.changeFeed);
    if (apiSocialClientOptions.problemFeed) socialClientOptions.problemFeed = MySupportFeed.fromApiEntity(apiSocialClientOptions.problemFeed);
    if (apiSocialClientOptions.purchaseFeed) socialClientOptions.purchaseFeed = MySupportFeed.fromApiEntity(apiSocialClientOptions.purchaseFeed);
    if (apiSocialClientOptions.knowledgeEntryFeed) socialClientOptions.knowledgeEntryFeed = MySupportFeed.fromApiEntity(apiSocialClientOptions.knowledgeEntryFeed);
    if (apiSocialClientOptions.serviceContractFeed) socialClientOptions.serviceContractFeed = MySupportFeed.fromApiEntity(apiSocialClientOptions.serviceContractFeed);
    if (apiSocialClientOptions.headlineFeed) socialClientOptions.headlineFeed = MySupportFeed.fromApiEntity(apiSocialClientOptions.headlineFeed);

    return socialClientOptions;
  }
}

export default SocialClientOptions;

export type SocialClientOptionsType = {
  id: number,
  name: string;
  customerDisplayRegistrationLink: string;
  defaultRegisterTitle: string;
  showForgotPasswordLink: string;
  defaultForgotPasswordTitle: string;
  forgotPasswordEmailExpiration: string;
  description: string;
  incidentDisplayWorkHistory: string;
  incidentAllowEmailToAssignee: string;
  changeUpdateEnabled: string;
  useMobileFeedLayout: string;
  incidentSubmitMessage: string;
  incidentSubmitDisplayCustomNumber: string;
  changeSubmitDisplayCustomNumber: string;
  purchaseSubmitDisplayCustomNumber: string;
  incidentLocationOverrideEnabled: string;
  incidentDisplayApprovalHistory: string;
  incidentDisplayApprovalNotification: string;
  problemCreateIncidentEnabled: string;
  changeSubmitMessage: string;
  changeDisplayApprovalHistory: string;
  changeDisplayApprovalAlertBar: string;
  changeDisplayAuditHistory: string;
  changeDisplayCorrespondenceHistory: string;
  changeDisplayCustomerWorkHistory: string;
  changeDisplaySlaHistory: string;
  changeDisplayRuleGroupHistory: string;
  incidentDisplayAuditHistory: string;
  incidentDisplaySlaHistory: string;
  incidentDisplayRuleGroupHistory: string;
  incidentDisplayCorrespondenceHistory: string;
  incidentDisplayCustomerChatHistory: string;
  incidentUpdateAssignee: string;
  incidentUpdateReceiptConfirmation: string;
  changeUpdateReceiptConfirmation: string;
  changeUpdateAssignee: string;
  purchaseDisplayApprovalAlertBar: string;
  purchaseRequestorSubmitterEnabled: string;
  purchaseSubmitMessage: string;
  changeLocationOverrideEnabled: string;
  serviceContractDisplayAuditHistory: string;
  serviceContractDisplayCorrespondenceHistory: string;
  serviceContractUseWithIncident: string;
  serviceContractUseWithChange: string;
  serviceContractNoContractMessage: string;
  serviceContractCourtesyTicketsEnabled: string;
  incidentDisplayGenericCustomerAuditHistory: string;
  changeDisplayGenericCustomerAuditHistory: string;
  bomgarIncidentDisplayNewSessionLink: string;
  bomgarIncidentCreateIncidentOnNewSessionStart: string;
  bomgarLoginRequiredForNewSession: string;
  bomgarDisplayAvailableReps: string;
  bomgarChatFlyoutEnabled: string;
  bomgarChatFlyoutTitle: string;
  bomgarChatFlyoutIcon: string;
  bomgarChatFlyoutContent: string;
  bomgarChatFlyoutDelay: string;
  bomgarMaxActiveEventsCount: string;
  homePageDisplayWelcomeMessage: string;
  homePageWelcomeMessage: string;
  homePageDisplayAssistBar: string;
  homePageRightSidePanel1Parameter: string;
  homePageRightSidePanel2Parameter: string;
  knowledgeEntryPageDisplayCategoryTree: string;
  knowledgeEntryPageDisplayCategoryTiles: string;
  knowledgeEntryPageWidget1Parameter: string;
  knowledgeEntryPageWidget2Parameter: string;
  incidentSelectCategoryText: string;
  changeSelectCategoryText: string;
  knowledgeSelectCategoryText: string;
  smsNotificationsEnabled: string;
  problemDisplayAuditHistory: string;
  problemDisplayCorrespondenceHistory: string;
  problemDisplayRuleGroupHistory: string;
  knowledgeEntryShowFollowLink: string;
  knowledgeEntryShowFollowButton: string;
  knowledgeEntryShowLikeButton: string;
  chatEnabled: string;
  chatAllowUnauthenticated: string;
  chatShowLinkOnIncident: string;
  chatRequestTimeoutLength: string;
  chatTimeoutMessage: string;
  chatTimeoutCreateIncidentButtonIncluded: string;
  chatShowGroupSelection: string;
  chatFlyoutEnabled: string;
  chatFlyoutTitle: string;
  chatFlyoutIcon: string;
  chatFlyoutContent: string;
  chatFlyoutDelay: string;
  newUsersRequireReview: string;
  newUsersRequireReviewMessage: string;
  loginBackgroundImage: string;
  loginBackgroundImageRepeat: string;
  knowledgeEntryShowHistoryContents: string;
  goToAssistShowLinkOnIncident: string;
  goToAssistClientUrl: string;
  goToAssistFlyoutEnabled: string;
  goToAssistFlyoutTitle: string;
  goToAssistFlyoutIcon: string;
  goToAssistFlyoutContent: string;
  goToAssistFlyoutDelay: string;
  incidentDisplayCategory: string;
  changeDisplayCategory: string;
  problemDisplayCategory: string;
  knowledgeEntryDisplayCategory: string;
  incidentEditCategory: string;
  changeEditCategory: string;
  incidentDisplayTabOrder: string;
  changeDisplayTabOrder: string;
  problemDisplayTabOrder: string;
  purchaseDisplayTabOrder: string;
  knowledgeEntryDisplayTabOrder: string;
  serviceContractDisplayTabOrder: string;
  incidentDisplayFieldOrder: string;
  changeDisplayFieldOrder: string;
  problemDisplayFieldOrder: string;
  purchaseDisplayFieldOrder: string;
  knowledgeEntryDisplayFieldOrder: string;
  serviceContractDisplayFieldOrder: string;
  incidentEditTabOrder: string;
  changeEditTabOrder: string;
  purchaseEditTabOrder: string;
  incidentEditFieldOrder: string;
  changeEditFieldOrder: string;
  purchaseEditFieldOrder: string;
  showCompanyOnRegistration: string;
  showPhoneOnRegistration: string;
  showCompanyOnIncidentSubmit: string;
  requireCompanyOnIncidentSubmit: string;
  showLocationOnIncidentSubmit: string;
  requireLocationOnIncidentSubmit: string;
  showPhoneOnIncidentSubmit: string;
  requirePhoneOnIncidentSubmit: string;
  showCompanyOnChangeSubmit: string;
  requireCompanyOnChangeSubmit: string;
  showLocationOnChangeSubmit: string;
  requireLocationOnChangeSubmit: string;
  showPhoneOnChangeSubmit: string;
  requirePhoneOnChangeSubmit: string;
  shippingCreateWorkItemIcon: string;
  shippingDisplaySelfHelpGuideIcon: string;
  shippingCreateDiscussionPostIcon: string;
  headerGaugeText: string;
  tiledNavigatorMaxColumns: string;
  assistBarTextOverride: string;
  customersCanAddDashboards: string;
  customerShowTimeZonePrompt: string;
  availableWidgets: string;
  pinNavigatorByDefault: string;
  sanitizeHtml: string;
  chatRepOtherDisplayName: string;
  incidentRouteMethod: IncidentRouteMethod;
  incidentDefaultPriority: IncidentPriority;
  purchaseHistoryTypesToDisplay: NewHistoryTypes;
  changeRouteMethod: IncidentRouteMethod;
  assistBarSearchEntityTypes: EntityTypes;
  homePageMainContentType: SocialClientHomePageMainContentType;
  homePageRightSidePanel1Type: SocialClientRightSidePanelType;
  homePageRightSidePanel2Type: SocialClientRightSidePanelType;
  knowledgeEntryPageWidget1Type: SocialClientRightSidePanelType;
  knowledgeEntryPageWidget2Type: SocialClientRightSidePanelType;
  globalAssistBarCreateEntityTypes: EntityTypes;
  chatButtomPosition: LayoutPositions;
  menuType: SocialClientMenuTypes;
  tiledNavigatorAlignment: HorizontalAlignment;
  incidentSubmitCompanyEntryType: CompanyEntryOptions;
  changeSubmitCompanyEntryType: CompanyEntryOptions;
  chatRepNameDisplayType: ExternalChatRepNameDisplayTypes;
  createWorkItemIcon: CustomIcon;
  displaySelfHelpGuideIcon: CustomIcon;
  createDiscussionPostIcon: CustomIcon;
  incidentDefaultOwner: SupportRepresentative;
  incidentDefaultOwnerGroup: Group;
  incidentDefaultStatus: IncidentStatus;
  incidentLoadBalancedRouteGroup: Group;
  incidentLoadBalancedRouteLocation: Location;
  incidentDefaultUrgencyImpactMapping: UrgencyImpactMapping;
  purchaseDefaultStatus: PurchaseStatus;
  changeDefaultOwner: SupportRepresentative;
  changeDefaultOwnerGroup: Group;
  changeDefaultStatus: ChangeStatus;
  changeLoadBalancedRouteGroup: Group;
  changeLoadBalancedRouteLocation: Location;
  changeDefaultUrgencyImpactMapping: UrgencyImpactMapping;
  changeDefaultCustomChangeType: CustomChangeType;
  theme: SocialClientTheme;
  bomgarIncidentTemplactForNewSessions: IncidentTemplate;
  globalAssistBarSelfHelpGuide: SelfHelpGuideItem;
  facebookIntegrationInfo: FacebookIntegrationInfo;
  twitterIntegrationInfo: TwitterIntegrationInfo;
  linkedInIntegrationInfo: LinkedInIntegrationInfo;
  forgotLoginTemplate: IncidentTemplate;
  knowledgeDiscussionNewsFeed: RepNewsFeedOptions;
  incidentTemplaceForCustomerRequiresReview: IncidentTemplate;
  viewIncidentLayout: IncidentLayout;
  submitIncidentLayout: IncidentLayout;
  viewChangeLayout: ChangeLayout;
  submitChangeLayout: ChangeLayout;
  viewProblemLayout: ProblemLayout;
  viewKnowledgeLayout: KnowledgeLayout;
  viewPurchaseLayout: PurchaseLayout;
  submitPurchaseLayout: PurchaseLayout;
  viewServiceContractLayout: ServiceContractLayout;
  headerGauge: QueryChart;
  customerProfileLayout: CustomerLayout;
  incidentFeed: MySupportFeed;
  changeFeed: MySupportFeed;
  problemFeed: MySupportFeed;
  purchaseFeed: MySupportFeed;
  knowledgeEntryFeed: MySupportFeed;
  serviceContractFeed: MySupportFeed;
  headlineFeed: MySupportFeed;
}

